# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Photonics & Quantum Systems
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Photonics and Quantum Systems (and Mathematical Optics) Group. 
  Design, implementation, and application of photonic and quantum 
  systems in metrology, communications, quantum computing, structured 
  light engineering, and nonlinear systems.
baseurl: ""
url: ""
link1: "arXiv:2307.04078v1"
desc1: "Multi-functional sensor based on photonic crystal fiber using plasmonic material and magnetic fluid"

link2: "https://doi.org/10.1088/1367-2630/ac77ab"
desc2: "A non-separability measure for spatially disjoint vectorial fields"

link3: "https://doi.org/10.1364/AO.456519"
desc3: "Violation of Bell’s inequality for Mathieu-Gauss vector modes"


include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

